[tools]
"ast-grep" = "latest"
"aws-cli" = "latest"
"bat" = "latest"
"btop" = "latest"
"cargo:bacon" = "latest"
"cargo:emacs-lsp-booster" = "latest"
"ccache" = "latest"
"cmake" = "latest"
"delta" = "latest"
docker-cli = "latest"
"eza" = "latest"
"fd" = "latest"
"fzf" = "latest"
"github-cli" = "latest"
"go" = "latest"
"jq" = "latest"
"just" = "latest"
"lazydocker" = "latest"
"lazygit" = "latest"
"lua" = "latest"
"neovim" = "latest"
"ninja" = "latest"
"node" = "lts"
opentofu = "latest"
"pixi" = "latest"
"pre-commit" = "latest"
"python" = "3"
"ripgrep" = "latest"
rust = "latest"
rust-analyzer = "latest"
"sccache" = "latest"
shellcheck = "latest"
"starship" = "latest"
"tree-sitter" = "latest"
"uv" = "latest"
"vivid" = "latest"
"zig" = "latest"
"zoxide" = "latest"

[env]
RUSTC_WRAPPER="sccache"
RUSTUP_TOOLCHAIN="" #prevent mise from overriding rustup-toolchain.toml

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]
