git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  nerdFontsVersion: "3"
  #catppuccin/lazygit macchiato teal
  theme:
    activeBorderColor:
      - '#8bd5ca'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8bd5ca'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

  authorColors:
    'Jacob Wujciak-Jens': '#a6da95'
    '*': '#c6a0f6'
