[[language]]
name = "python"
language-servers = ["pylsp"]

[language-server.ruff.config.settings]
lineLength = 100

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true
