[tools]
"ast-grep" = "latest"
"cargo:bacon" = "latest"
"bat" = "latest"
"btop" = "latest"
"ccache" = "latest"
"cmake" = "latest"
"delta" = "latest"
"eza" = "latest"
"fd" = "latest"
"fzf" = "latest"
"github-cli" = "latest"
"go" = "latest"
"jq" = "latest"
"just" = "latest"
"lazydocker" = "latest"
"lazygit" = "latest"
"lua" = "latest"
"neovim" = "latest"
"ninja" = "latest"
"node" = "lts"
"pixi" = "latest"
"pre-commit" = "latest"
"python" = "3"
"ripgrep" = "latest"
"rust" = { version = "latest", profile = "default"}
"rust-analyzer" = "latest"
"sccache" = "latest"
"starship" = "latest"
"tree-sitter" = "latest"
"uv" = "latest"
"vivid" = "latest"
"zig" = "latest"
"zoxide" = "latest"

